export const AUTH_BUTTON_CODES = {
  USER_CREATE: 'AUTH_USER_CREATE',
  USER_EDIT: 'AUTH_USER_EDIT',
  USER_ASSIGN: 'AUTH_USER_ASSIGN',
  USER_RESET_PASSWORD: 'AUTH_USER_RESET_PASSWORD',
  USER_CHANGE_PASSWORD: 'AUTH_USER_CHANGE_PASSWORD',
  USER_DELETE: 'AUTH_USER_DELETE',

  ROLE_CREATE: 'AUTH_ROLE_CREATE',
  ROLE_EDIT: 'AUTH_ROLE_EDIT',
  ROLE_DELETE: 'AUTH_ROLE_DELETE',

  ORG_CREATE: 'AUTH_ORG_CREATE',
  ORG_EDIT: 'AUTH_ORG_EDIT',
  ORG_DELETE: 'AUTH_ORG_DELETE',

  MENU_CREATE: 'AUTH_MENU_CREATE',
  MENU_EDIT: 'AUTH_MENU_EDIT',
  MENU_DELETE: 'AUTH_MENU_DELETE',

  BUTTON_CREATE: 'AUTH_BUTTON_CREATE',
  BUTTON_EDIT: 'AUTH_BUTTON_EDIT',
  BUTTON_DELETE: 'AUTH_BUTTON_DELETE',

  PERMISSION_CREATE: 'AUTH_PERMISSION_CREATE',
  PERMISSION_EDIT: 'AUTH_PERMISSION_EDIT',
  PERMISSION_DELETE: 'AUTH_PERMISSION_DELETE',

  DATA_SCOPE_CREATE: 'AUTH_DATA_SCOPE_CREATE',
  DATA_SCOPE_EDIT: 'AUTH_DATA_SCOPE_EDIT',
  DATA_SCOPE_DELETE: 'AUTH_DATA_SCOPE_DELETE',

  ONLINE_USER_KICK_OUT: 'AUTH_ONLINE_USER_KICK_OUT',
} as const;

export const AUTH_BUTTON_PERMISSION_CODES = [
  AUTH_BUTTON_CODES.PERMISSION_CREATE,
  AUTH_BUTTON_CODES.PERMISSION_EDIT,
  AUTH_BUTTON_CODES.PERMISSION_DELETE,
] as const;

export const AUTH_BUTTON_MANAGEMENT_CODES = [
  AUTH_BUTTON_CODES.BUTTON_CREATE,
  AUTH_BUTTON_CODES.BUTTON_EDIT,
  AUTH_BUTTON_CODES.BUTTON_DELETE,
] as const;
